### PR TITLE
feat(layout): setup of navbar and footer

### LINKED ISSUE #11: [General] Setup main layout
**Task title**
Setup main layout

**Task description**
Setup the main layout consisting of header and footer.

**Subtasks**
- [x] Add navbar
- [x] Add logo
- [x] Add signup and signin (unsigned)
- [ ] Add user icon (signed)
- [x] Add footer with links

**Screenshots**

Image

Image

**Link to the component on Figma**
https://www.figma.com/file/IEhYhDLnrHmUuYercEZUjA/Pebble-work?node-id=1830-8562&t=T4zHEMAENyzMmQGs-4 (unsigned)
https://www.figma.com/file/IEhYhDLnrHmUuYercEZUjA/Pebble-work?node-id=1830-8462&t=T4zHEMAENyzMmQGs-4 (signed)
https://www.figma.com/file/IEhYhDLnrHmUuYercEZUjA/Pebble-work?node-id=1830-7131&t=T4zHEMAENyzMmQGs-4 (footer)

### PR DESCRIPTION
**Pull request by iiAbady**
# What does this pull request do?
## This pull request is a feature that adds the main layout components: navbar and footer. Alongside them, are tests.

### CODE REVIEW

**Review by SufyanCS — COMMENTED** [review]
1- add padding to the logo and the change language icon
aa
2- add responsive design for tablet and mobile
3- Try to break the navbar into smaller components
4- Fix all errors that shows  in the console
5- add links path to the sign in/up buttons

**Comment by iiAbady** [comment]
> 1- add padding to the logo and the change language icon aa 2- add responsive design for tablet and mobile 3- Try to break the navbar into smaller components 4- Fix all errors that shows in the console 5- add links path to the sign in/up buttons

As for the console errors, I'll fix them but there is one console warn related to i18-next that I can't fix. (see: https://github.com/i18next/next-i18next/issues/1917)

**Review by adeeb-samad — COMMENTED** [review]
Done

**Comment by sulmi24** [comment]
Thank you for submitting the pull request. 
Overall, this pull request looks good, but I have a few suggestions for improvement:

- Please make sure to add sufficient **margin and padding to the design for the Logo.**
image


- The design needs to be made responsive for mobile and tablet devices.
image

- Tryalign the social media icons with the page links on the footer.

Keep up the good work!"

**Review by sulmi24 — CHANGES_REQUESTED** [review]
Thank you for submitting the pull request.
Overall, this pull request looks good, but I have a few suggestions for improvement:

Please make sure to add sufficient margin and padding to the design for the Logo.
image
The design needs to be made responsive for mobile and tablet devices.
image

Tryalign the social media icons with the page links on the footer.

Keep up the good work!"

**Comment by iiAbady** [comment]
@sulmi24 Did the changes by having better responesivness, I think this is ready to be merged.

**Review by HamadBakeel — APPROVED** [review]
everything looks better so far and yet to be enhanced in future updated fixes

**Review by SufyanCS — APPROVED** [review]

**Review by adeeb-samad — APPROVED** [review]
Done

**Review by adeeb-samad — APPROVED** [review]
Done

**Review by sulmi24 — APPROVED** [review]
**Ready to go** 
The PR looks good

**Pull request merged**
