### PR TITLE
feat(landing): add `sustainable development goals` section

### LINKED ISSUE #8: [Landing Page] Add sustainable development goals section
**Task title**
Add sustainable development goals section

**Task description**
Add sustainable development goals section with each goal as a rounded image.

**Subtasks**
- [ ] Add goal component
- [ ] Add goals component
- [ ] Add title
- [ ] Add description

**Screenshots**

Image

**Link to the component on Figma**
https://www.figma.com/file/IEhYhDLnrHmUuYercEZUjA/Pebble-work?node-id=1830-7086&t=T4zHEMAENyzMmQGs-4

### PR DESCRIPTION
**Pull request by iiAbady**
## **Describe what does this pull request do?**

This pull request adds the sustainable development goals section along side its tests and refactoring of mini components.

### CODE REVIEW

**Review by adeeb-samad — CHANGES_REQUESTED** [review]
we have to fetch SDGs from unstate.un..org

**Comment by iiAbady** [comment]
> we have to fetch SDGs from unstate.un..org

I took them from the design.

**Review by SufyanCS — CHANGES_REQUESTED** [review]
Excellent work, @iiAbady , To optimize the code consider creating an array that includes all the required data (src, width, and height...) and then use the map() method to generate the images dynamically, rather than writing out each image manually.

**Comment by iiAbady** [comment]
> Excellent work, @iiAbady , To optimize the code consider creating an array that includes all the required data (src, width, and height...) and then use the map() method to generate the images dynamically, rather than writing out each image manually.

Will do for sure!

**Review by adeeb-samad — APPROVED** [review]
Done

**Review by SufyanCS — APPROVED** [review]
Great Work @iiAbady! Keep going.

**Pull request merged**
