### PR TITLE
Feature/firebase configuration

### LINKED ISSUE #65: Set up Firebase API and authentication
1. Create a Firebase project.
2. Set up Firestore
3. Add Firebase to your app
4. build the Firebase config
5. build the Firebase Rules
6.  React hook called useFirestore that takes in a collection path as a parameter, and returns an object with methods to add, update, delete, and get documents from a Firestore collection, as well as the current documents in that collection.

### PR DESCRIPTION
**Pull request by sulmi24**
### Added Firebase and set up Firestore for the app

Description:

- I added Firebase to the project and set up Firestore to allow for data storage and retrieval. I also created a custom hook called useFirestore to handle data operations in Firestore.

**Changes Made:**

- Imported initializeApp, getApps, and getApp from "firebase/app"
- Imported "firebase/firestore"
- Created a firebaseConfig object to hold the Firebase project's configuration details
- Initialized Firebase if it hasn't been initialized yet
- Created a useFirestore custom hook to handle data operations in Firestore
- Defined addDocument, updateDocumentById, deleteDocument, and getDocumentById functions to interact with Firestore
- Exported useFirestore hook for use in other files
- Added baseUrl and paths properties to compilerOptions in tsconfig.json
- Added storage and firestore properties to firebase.json

**Instructions to Follow:**

- To use the useFirestore hook in other files, import it like this:

1. To use the useFirestore hook, you need to pass the collection path as a parameter when calling the hook.
2.  import the useFirestore hook in other files 
`import useFirestore from "@/lib/useFirestore";`
3.  initialize it with a collection name
`const { addDocument, documents } = useFirestore("test");`
4. You can create other hooks for authentication or storage by following the same pattern as the useFirestore hook.

From there, you can use the addDocument, updateDocumentById, deleteDocument, and getDocumentById functions to interact with Firestore data. You can also create other hooks for auth or storage following the same pattern of this file.

### CODE REVIEW

**Review by adeeb-samad — APPROVED** [review]
Done

**Review by SufyanCS — APPROVED** [review]
Great work!

**Review by iiAbady — APPROVED** [review]
Well done @sulmi24

**Comment by iiAbady** [comment]
@sulmi24 I'm wondering if you can add a `useAuth` hook to make easier to do authentication in the whole app.

**Pull request merged**
